### ISSUE TITLE
More asymmetry options

### ISSUE THREAD

**Issue by lplume** [8bitskull/dicebag#5]
Hello @8bitskull!

I've found out we're implementing something starting from the same source. I would love to hear your thoughts about how to implement "custom" behavior/asymmetry, such as the "critical hits" example.
Do you think that adding a way to pass in user defined functions could be beneficial? Since it's something that usually would affect the final result that way might be usless/reduntant/code bloating?

Something like that could be as the following code

```lua
-- dice module
function roll(dice, callback)
  result = math.random(dice)
  return callback(dice, result)
end

-- user
dm = require('dicemodule')

doubleup = function (dice, result)
  value = result
  if (result == dice) then value = result * 2 end
  return value
end

dm.roll(6, doubleup)
```
Thanks for your attention and the effort on this module!

**Comment by 8bitskull** [comment]
Hi @lplume and thanks for your kind words!

I have to admit that while I think I understand more or less what you're asking for, it's a bit more complicated than what I'm used to. I'm not sure I could implement the functionality, and I wouldn't be comfortable maintaining it anyway. 

I was thinking of suggesting that you monkey patch some of the functions, but I'm not actually sure that would achieve what you're looking for. Sorry - not a very helpful answer!

**Comment by lplume** [comment]
Try to rewrite ^^

I've found out we're implementing a pretty similar dice probability module, inspired by RedBlob [Probability and Games: Damage Rolls](https://www.redblobgames.com/articles/probability/damage-rolls.html) blog post.
Since we're referring to the same blog, I would love to hear if you have any thoughts/interests/insights on about how to tackle the subject of asymmetry other than "rerolling" and dropping outcomes. I was wondering if such libraries might benefits of a built in way to alter the distribution.
In order to achieve this my first idea was to give the ability to call functions (for instance dicebag.roll_dice(num_dice, num_sides, modifier)) with an optional user defined function that can alter the distribution itself within the library.

Let's immagine the "critical hits" scenario: on a critical hit the damage will be doubled. Consider the following deliberately simplified examples:

```lua
-- In this example I immagine how to use dicebag on a likely real world code

-- damage_system.lua
-- lets pretend this is a class/module
local db = require('dicebag')

function hit()
  return db.roll_dice(1, 20)
end

function damage(hit)
  local damage = db.roll_dice(1, 6)

  if hit == 20 then
    damage = damage * 2
  elseif hit == 1 then
    damage = damage + 1
  end

  return damage
end

-- somewhere else
ds = require('damage_system')

local hit = ds.hit()
local d = ds.damage(hit)
```

The different approach I am wondering on is something like

```lua
-- This example aim to immagine a different approach, in which dicebag
-- have builtin abilities to alter results

-- dicebag.lua
function M.roll_dice(num_dice, num_sides, modifier, callback)

    num_dice = num_dice or 1
    num_sides = num_sides or 6
    modifier = modifier or 0
    callback = callback or nil

    local result = modifier

    for i=1,num_dice do
        result = result + math.random(num_sides)
    end

    if callback then
      result = callback(num_sides, result) -- parameters here are just simple example
    end
    
    return result
end

-- damage_system.lua
local db = require('dicebag')

critical = function (dice, result)
  return result * 2
end

critical_failure = function (dice, result) -- let's say we're in easy mode
  return result + 1
end

function hit()
  return db.roll_dice(1,20)
end

function damage(hit)
  local mod = nil
  if hit == 20 then
    mod = critical
  elseif hit == 1 then
    mod = critical_failure
  end
  
  return db.roll_dice(1, 6, 0, mod)    
end

-- somewhere else
ds = require('damage_system')

local hit = ds.hit()
local d = ds.damage(hit)
```

[edit]
more on this: the benefit could be to give the user more control over the results without patching the library itself. The callback could receive additional intermediary parameters in order to gain more control on the overall result itself
[/edit]

Hope this could explain my question, along the line "would love to hear thoughts about this", feel free to give or not any thoughts.

Thanks again!

**Comment by 8bitskull** [comment]
I think in the end, for either of your methods the end user will need to write custom functions one way or another. Because the outcome is achievable in different ways (e.g. either callbacks built into the module or custom functions on top of the module), I think it becomes a matter of personal preference. In my opinion, then, I would prefer the module does its basic functionality, and it is up to the user to create what they want on top of the module.

Specifically, if I was going to implement critical hits or dropping/re-rolling, then I would prefer to implement those specific functions rather than build in customisation functionality. Does that make sense?

**Comment by lplume** [comment]
100% it makes sense, also I think it's a matter of what the library want to be. Thanks for the chat about the topic!
